name: CI pipeline

on:
  push:

jobs:

  pytest:
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./lintuasema-backend
    - name: Test with pytest
      run: |
        pip install pytest
        python3 -m pytest
      working-directory: ./lintuasema-backend

  cypress-test:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./lintuasema-backend
    - name: Run backend
      run: flask run &
      working-directory: ./lintuasema-backend
      
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install
      run: npm install
      working-directory: ./frontend
    - name: npm build
      run: npm run build --if-present
      working-directory: ./frontend
    - name: run frontend
      run: npm start &
      working-directory: ./frontend
    - name: setup cypress test
      uses: actions/setup-node@v1
      with:
        wait-on: http://localhost:3000
    - name: run cypress test
      run: npm run cypress:cmd
      working-directory: ./frontend

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Build the Docker image
        run: docker build . --file Dockerfile -t test

  deploy:
    runs-on: ubuntu-latest
    needs: [cypress-test, pytest, docker-build]

    steps:
    - name: Webhook
      uses: distributhor/workflow-webhook
      with:
        url: "https://rahti.csc.fi:8443/apis/build.openshift.io/v1/namespaces/lintuasema-staging/buildconfigs/lintuasema-build/webhooks/b033e6aae4979ed3/github"
        #json: '{ "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}", "created_at": "${{github.event.push.created_at}}", "updated_at": "${{github.event.push.updated_at}}" }'
        
