name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Build the Docker image
        run: docker build . --file Dockerfile -t test
        
      - name: npm install
        run: npm install
        
      - name: Run cypress tests
        run: npm run cypress:cmd
