name: CI pipeline

on:
  push:

jobs:

  pytest:
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./lintuasema-backend
    - name: Test with pytest
      run: |
        pip install pytest
        python3 -m pytest
      working-directory: ./lintuasema-backend

  cypress-test:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./lintuasema-backend
    - name: Run backend
      run: flask run &
      working-directory: ./lintuasema-backend
      
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install
      run: npm install
      working-directory: ./frontend
    - name: npm build
      run: npm run build --if-present
      working-directory: ./frontend
    - name: run frontend
      run: npm start &
      working-directory: ./frontend
    - name: Cypress run
      uses: cypress-io/github-action@v1
      with:
        record: true
        start: npm run cypress:cmd
        wait-on: http://localhost:3000
        working-directory: ./frontend

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Build the Docker image
        run: docker build . --file Dockerfile -t test


        
